/* SPDX-License-Identifier: GPL-3.0-or-later */
flash_boost_control_rpm_axis = 0x625c6;
flash_boost_control_tps_axis = 0x62648;
sst_mode_flags = 0x80a650;
current_sst_gear = 0x80a2e6;
boost_target_load = 0x808b52;
temp_axis_src = 0x808588;
run_state_flags = 0x808814;
mut_actuator_tests0 = 0x808c3a;
wastegate_base_duty = 0x80a91a;
wastegate_base_duty_for_correction = 0x808b4e;
tps_target = 0x8086f2;
tps_target_correction = 0x804510;
iat = 0x808650;

vehicle_speed_frequency = 0x8087dc;
fuel_map_target_afr = 0x8088f0;
update_fuel_map_target_afr = 0x1cd50;
update_fuel_map_target_afr_call_location = 0x1c9e8;
get_fuel_map_load_source = 0x1ce40;
flash_fuel_map_rpm_axis = 0x60f0c;
flash_fuel_map_load_axis = 0x60f32;

get_mapped_spark_advance = 0x21748;
get_mapped_spark_advance_call_location = 0x20918;

flash_sst_mode_selection_supersport_vehicle_speed_frequency_max = 0x5447c;

flash_mivec_target_rpm_axis = 0x615ea;
flash_mivec_target_load_axis = 0x615ba;

flash_intake_mivec_target_3dmap8 = 0x5db52;

flash_mdp_load_rpm_axis = 0x62a3a;
flash_mdp_load_mdp_axis = 0x62a66;

flash_mdp_load_mivec_target_3dmap16 = 0x60486;
