/* SPDX-License-Identifier: GPL-3.0-or-later */
flash_icomp_base_neutral_1a_2dmap8 = 0x8680;
flash_icomp_base_neutral_1b_2dmap8 = 0x8674;
flash_icomp_base_neutral_2a_2dmap8 = 0x6e52;
flash_icomp_base_neutral_2b_2dmap8 = 0x5c6e;
flash_icomp_base_neutral_3a_2dmap8 = 0x6e46;
flash_icomp_base_neutral_3b_main_2dmap8 = 0x3e36;

flash_icomp_base_drive1_2dmap8 = 0x868c;
flash_icomp_base_drive2_2dmap8 = 0x5c7a;
flash_icomp_base_drive3_main_2dmap8 = 0x5822;

flash_target_idle_rpm_neutral_1a_2dmap8 = 0x86a4;
flash_target_idle_rpm_neutral_1b_2dmap8 = 0x8698;
flash_target_idle_rpm_neutral_2a_2dmap8 = 0x3dee;
flash_target_idle_rpm_neutral_2b_2dmap8 = 0x3de2;
flash_target_idle_rpm_neutral_3a_2dmap8 = 0x3dd6;
flash_target_idle_rpm_neutral_3b_main_2dmap8 = 0x3dca;

flash_target_idle_rpm_drive1_2dmap8 = 0x86b0;
flash_target_idle_rpm_drive2_2dmap8 = 0x3e06;
flash_target_idle_rpm_drive3_main_2dmap8 = 0x3dfa;

flash_idle_coolant_axis = 0x9d60;
