/* SPDX-License-Identifier: GPL-3.0-or-later */
flash_maf_compensations_rpm_axis = 0xfef8;
flash_default_maf_scaled1_base_vs_rpm_2dmap16 = 0xc08e;
flash_maf_charge_max_base_vs_rpm_2dmap16 = 0xc220;
flash_maf_charge_min = 0x9802;
flash_maf_low_tps_vs_rpm_2dmap8 = 0xc0ac;
flash_maf_baro_pressure_compensation_axis = 0xff16;

flash_manifold_vacuum_axis = 0x10002;
flash_fuel_vs_mdp_compensation_2dmap8 = 0xc3b8;

flash_fuel_temperature_sensor_axis = 0x171ac;
flash_fuel_temperature_sensor_characteristic_2dmap16 = 0x170b4;


warmup_fuel_correction = 0x8050ea;
maf_charge_max_compensated = 0x804fa8;
maf_charge_min_compensated = 0x804fac;
maf_charge_max = 0x804fa4;
maf_charge_min = 0x804faa;

adc_full_fuel_temperature = 0x804f20;
adc_full_fuel_tank_pressure = 0x804f1c;

temp_axis_src = 0x804dca;
engine_rpm = 0x804f48;
baro_pressure = 0x804ee6;

default_maf_scaled1 = 0x8057fe;
fp12256_f16 = 0x805020;

flash_mut_variables_table = 0x3d50c;

flash_mode_flags0_init = 0x826e;
flash_mode_flags1_init = 0x827e;
flash_mode_flags2_init = 0x828e;
flash_mode_flags3_init = 0x829e;
flash_mode_flags4_init = 0x82ae;
flash_mode_flags5_init = 0x82be;

flash_romid = 0x8226;

adc_run = 0x18f5c;
get_ig1 = 0x17bb8;
