# SPDX-License-Identifier: GPL-3.0-or-later
SOURCES = ../../../src/templates/cvt_overboost_protection.c

ELF_OUT_FILE    = 35740031.elf
BIN_OUT_FILE    = $(OUT_DIR)/35740031_patched.bin
XML_PATCH_FILE  = $(OUT_DIR)/35740031_patches.xml
XML_HEADER_FILE = 35740031_header.xml
XML_OUT_FILE    = $(OUT_DIR)/35740031.xml

include ../common.mk
