/* SPDX-License-Identifier: GPL-3.0-or-later */
flash_shift_oss_tps_axis = 0x938c;
flash_1st_to_2nd_shift_normal_tarmac_oss_vs_tps_2dmap8 = 0x9b6c;
flash_2nd_to_3rd_shift_normal_tarmac_oss_vs_tps_2dmap8 = 0x9bb4;
flash_3rd_to_4th_shift_normal_tarmac_oss_vs_tps_2dmap8 = 0x9bfc;
flash_4th_to_5th_shift_normal_tarmac_oss_vs_tps_2dmap8 = 0x9c44;

flash_2nd_to_1st_shift_normal_tarmac_oss_vs_tps_2dmap8 = 0x9d64;
flash_3rd_to_2nd_shift_normal_tarmac_oss_vs_tps_2dmap8 = 0x9d1c;
flash_4th_to_3rd_shift_normal_tarmac_oss_vs_tps_2dmap8 = 0x9cd4;
flash_5th_to_4th_shift_normal_tarmac_oss_vs_tps_2dmap8 = 0x9c8c;

atshift_current_gear = 0x80450e;
atshift_target_gear = 0x804510;
agpins1_processed = 0x804336;
