# SPDX-License-Identifier: GPL-3.0-or-later
ROM_HINT = (Pajero Sport diesel AT ECU)

SOURCES = ../../../src/templates/at_shift.c \
	../../../src/at/pajero_manual_indicator.c \
	../../../src/at/pajero_manual_indicator_data.c

ELF_OUT_FILE    = 8631B0190A.elf
BIN_OUT_FILE    = $(OUT_DIR)/8631B0190A_patched.bin
XML_PATCH_FILE  = $(OUT_DIR)/8631B0190A_patches.xml
XML_HEADER_FILE = 8631B0190A_header.xml
XML_OUT_FILE    = $(OUT_DIR)/8631B0190A.xml

include ../common.mk
