// SPDX-License-Identifier: GPL-3.0-or-later
#define RXDATA0_INIT_DATA_POINTER 2
#define RXDATA0_WRITE_MEMORY_DATA 3
#define RXDATA0_READ_MEMORY_DATA0 4
#define RXDATA0_5_DEPRECATED_ERROR48 5
#define RXDATA0_CAN_LOG_TIME_BASED_INIT 6
/*if data[2] not zero - stops time based logs too*/
#define RXDATA0_CLOSE_SESSION 7
#define RXDATA0_CAN_LOG_TIME_START_STOP 8
/*broken*/
#define RXDATA0_GET_VIRTUAL_FLASH_RAM_POINTER 9
#define RXDATA0_10_DEPRECATED_ERROR48
#define RXDATA0_11_DEPRECATED_ERROR48
#define RXDATA0_12_DEPRECATED_ERROR48
#define RXDATA0_13_DEPRECATED_ERROR48
#define RXDATA0_GET_FLASH_BLOCK_CRC 14
#define RXDATA0_READ_MEMORY_DATA_FROM 15
#define RXDATA0_16_DEPRECATED_ERROR48 16
#define RXDATA0_VIRTUAL_FLASH_CONTROL 17
#define RXDATA0_GET_RANDOM_NUMBER 18
#define RXDATA0_CRYPTO_INIT_FLAGS 19
#define RXDATA0_CAN_LOG_TIME_BASED_INIT_INSTANCE 20
#define RXDATA0_CAN_LOG_TIME_BASED_INIT_INSTANCE2 21
#define RXDATA0_CAN_LOG_TIME_BASED_INIT_FRAME_DATA 22
#define RXDATA0_GET_ENG_TRANS_STRING 23
#define RXDATA0_24_DEPRECATED_ERROR48 24
#define RXDATA0_INIT_SOME_SIZE 25
#define RXDATA0_26_DEPRECATED_ERROR48 26
#define RXDATA0_GET_VERSION_2_1_MAYBE 27
#define RXDATA0_28_DEPRECATED_ERROR48
#define RXDATA0_29_DEPRECATED_ERROR48
#define RXDATA0_30_DEPRECATED_ERROR48
#define RXDATA0_31_DEPRECATED_ERROR48
#define RXDATA0_32_DEPRECATED_ERROR48
#define RXDATA0_33_DEPRECATED_ERROR48
#define RXDATA0_34_DEPRECATED_ERROR48
#define RXDATA0_WRITE_MEMORY_DATA2 35
