// SPDX-License-Identifier: GPL-3.0-or-later
#ifndef LAUNCH_CONTROL_H
#define LAUNCH_CONTROL_H

#define LAUNCH_CONTROL_APPS_HIGH 0x01
#define LAUNCH_CONTROL_ON 0x02
#define LAUNCH_CONTROL_FUEL_ENRICHMENT 0x04
#define LAUNCH_CONTROL_SPARK_LIMIT 0x08
#define LAUNCH_CONTROL_RPM_HOLD 0x10
#define LAUNCH_CONTROL_FUEL_CUT 0x20
#define LAUNCH_CONTROL_ACTIVE_ACTIONS                                                                                  \
	(LAUNCH_CONTROL_FUEL_ENRICHMENT | LAUNCH_CONTROL_SPARK_LIMIT | LAUNCH_CONTROL_RPM_HOLD)

#endif /*LAUNCH_CONTROL_H*/
